<attr>
VERSION:0
GROUP:[0]
<end>
<pos>
<end>
<program>

PRINTF "哈哈哈哈哈哈哈哈哈哈1111111111aBaBaBaBaBaBaBaBaBaB,./，。、  ?!"R[1];"哈哈哈哈哈哈哈哈哈哈1111111111aBaBaBaBaBaBaBaBaBaB,./，。、  ?!"R[2];"哈哈哈哈哈哈哈哈哈哈1111111111aBaBaBaBaBaBaBaBaBaB,./，。、  ?!"R[3];"哈哈哈哈哈哈哈哈哈哈1111111111aBaBaBaBaBaBaBaBaBaB,./，。、  ?!"R[4];"哈哈哈哈哈哈哈哈哈哈1111111111aBaBaBaBaBaBaBaBaBaB,./，。、  ?!"R[5];"哈哈哈哈哈哈哈哈哈哈1111111111aBaBaBaBaBaBaBaBaBaB,./，。、  ?!"R[6];"哈哈哈哈哈哈哈哈哈哈1111111111aBaBaBaBaBaBaBaBaBaB,./，。、  ?!"R[7];"哈哈哈哈哈哈哈哈哈哈1111111111aBaBaBaBaBaBaBaBaBaB,./，。、  ?!"R[8];"哈哈哈哈哈哈哈哈哈哈1111111111aBaBaBaBaBaBaBaBaBaB,./，。、  ?!"R[9];"哈哈哈哈哈哈哈哈哈哈1111111111aBaBaBaBaBaBaBaBaBaB,./，。、  ?!"R[10]
<end>