<attr>
VERSION:0
GROUP:[0]
<end>
<pos>
<end>
<program>

PRINTF "aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee"R[1];"aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee"R[2];"aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee"R[3];"aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee"R[4];"aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee"R[5];"aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee"R[6];"aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee"R[7];"aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee"R[8];"aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee"R[9];"aaaaaaaaaabbbbbbbbbbccccccccccddddddddddeeeeeeeeee"R[10]
<end>